plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.arizatakip.system'
    compileSdk 34

    defaultConfig {
        applicationId "com.arizatakip.system"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            buildConfigField "String", "API_BASE_URL", "\"https://dev-api.com/\""
            buildConfigField "boolean", "DEBUG_LOGGING", "true"
        }
        release {
            minifyEnabled false
            buildConfigField "String", "API_BASE_URL", "\"https://api.com/\""
            buildConfigField "boolean", "DEBUG_LOGGING", "false"
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
        dataBinding true
        buildConfig true
    }
}

dependencies {

    // Core
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.constraintlayout)

    // Retrofit
    implementation(libs.retrofit)
    implementation(libs.retrofit.gson)

    // OkHttp
    implementation(libs.okhttp)
    implementation(libs.okhttp.logging)

    // Room
    implementation(libs.room.runtime)
    annotationProcessor(libs.room.compiler)

    // Lifecycle
    implementation(libs.lifecycle.viewmodel)
    implementation(libs.lifecycle.livedata)

    // Firebase
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.auth)
    implementation(libs.firebase.database)

    // Gson
    implementation(libs.gson)

    // Charts
    implementation(libs.mpandroidchart)

    // Test
    testImplementation(libs.junit)
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
}